[package]
name = "webserver"
version = "0.1.0"
authors = ["Sudeep Kumar <sudeepdino008@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signal-hook = "0.1.7"